#!/usr/bin/env bash
# Declares the game's languages in the iOS project generated by
# `flutter create`, as Flutter asks of localized iOS apps.
set -euo pipefail

plist=ios/Runner/Info.plist
/usr/libexec/PlistBuddy -c "Delete :CFBundleLocalizations" "$plist" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :CFBundleLocalizations array" "$plist"
for language in fr en es; do
  /usr/libexec/PlistBuddy -c "Add :CFBundleLocalizations: string $language" "$plist"
done
