#!/usr/bin/env bash
# Replaces the default Flutter icon with the Abyss icon in the platform
# folders generated by `flutter create`. Run after `flutter pub get`.
set -euo pipefail

present() { [ -e "$1" ] && echo true || echo false; }
android=$(present android/app/src/main/AndroidManifest.xml)
ios=$(present ios/Runner.xcodeproj)
web=$(present web/index.html)

# flutter_launcher_icons fails on a missing platform folder, and CI creates
# one platform per job: only enable the platforms present.
# Adaptive icon settings alone would make it write Android files.
drop_android=$([ "$android" = true ] && echo '' || echo '/(adaptive_icon|min_sdk_android)/d')
# Portable between GNU (Linux runners) and BSD (macOS runner) tools.
config=$(mktemp "${TMPDIR:-/tmp}/launcher_icons.XXXXXX")
trap 'rm -f "$config"' EXIT
sed -E -e "s/^  android: true/  android: $android/" \
    -e "s/^  ios: true/  ios: $ios/" \
    -e "s/^    generate: true/    generate: $web/" \
    -e "$drop_android" \
    flutter_launcher_icons.yaml > "$config"
dart run flutter_launcher_icons -f "$config"

# The full icon is unreadable at 16 px: the favicon is a tighter crop.
if [ "$web" = true ]; then
  cp assets/app_icon/favicon.png web/favicon.png
fi
