#!/usr/bin/env bash
# Replaces the default Flutter icon with the Abyss icon in the platform
# folders generated by `flutter create`. Run after `flutter pub get`.
set -euo pipefail

present() { [ -e "$1" ] && echo true || echo false; }
android=$(present android/app/src/main/AndroidManifest.xml)
ios=$(present ios/Runner.xcodeproj)
web=$(present web/index.html)

# flutter_launcher_icons fails on a missing platform folder, and CI creates
# one platform per job: only enable the platforms present.
config=$(mktemp --suffix=.yaml)
trap 'rm -f "$config"' EXIT
sed -e "s/^  android: true/  android: $android/" \
    -e "s/^  ios: true/  ios: $ios/" \
    -e "s/^    generate: true/    generate: $web/" \
    flutter_launcher_icons.yaml > "$config"
if [ "$android" = false ]; then
  # Adaptive icon settings alone would make it write Android files.
  sed -i -e '/adaptive_icon/d' -e '/min_sdk_android/d' "$config"
fi
dart run flutter_launcher_icons -f "$config"

# The full icon is unreadable at 16 px: the favicon is a tighter crop.
if [ "$web" = true ]; then
  cp assets/app_icon/favicon.png web/favicon.png
fi
