enum ActionType {
  upgradeBuilding,
  unlockBranch,
  researchTech,
  recruitUnit,
  explore,
  collectTreasure,
  fightMonster,
  descend,
  sendReinforcements,
  attackTransitionBase,
  attackBase,
  announceAttack,
  attackVolcanicKernel,
  garrisonKernel,
  chooseEvent,
  endTurn,
}
