/// Injects the web splash into the `web/index.html` generated by
/// `flutter create`. Pure string transform: idempotent, so running it again
/// replaces the previous splash instead of adding a second one.
library;

const String cssStart = '<!-- abyss-splash:css -->';
const String cssEnd = '<!-- /abyss-splash:css -->';
const String bodyStart = '<!-- abyss-splash:body -->';
const String bodyEnd = '<!-- /abyss-splash:body -->';

/// Returns [indexHtml] with [css] in the head and [markup] at the top of the
/// body, each wrapped in marker comments.
String applySplash(
  String indexHtml, {
  required String css,
  required String markup,
}) {
  final clean = removeSplash(indexHtml);
  final headClose = clean.indexOf('</head>');
  final bodyOpen = RegExp(r'<body[^>]*>').firstMatch(clean);
  if (headClose < 0 || bodyOpen == null || bodyOpen.start < headClose) {
    throw const FormatException('index.html has no </head> then <body>');
  }
  final head = '$cssStart\n<style>\n${css.trim()}\n</style>\n$cssEnd\n';
  final body = '\n$bodyStart\n${markup.trim()}\n$bodyEnd';
  return clean.substring(0, headClose) +
      head +
      clean.substring(headClose, bodyOpen.end) +
      body +
      clean.substring(bodyOpen.end);
}

/// Removes any splash previously injected by [applySplash].
String removeSplash(String indexHtml) {
  return indexHtml
      .replaceAll(_block(cssStart, cssEnd, leading: false), '')
      .replaceAll(_block(bodyStart, bodyEnd, leading: true), '');
}

RegExp _block(String start, String end, {required bool leading}) {
  final body = '${RegExp.escape(start)}[\\s\\S]*?${RegExp.escape(end)}';
  return RegExp(leading ? '\\n?$body' : '$body\\n?');
}
